### ISSUE TITLE
complete-guide-to-forza-horizon-5-badges : Horizon Retrowave

### ISSUE THREAD

**Issue by EDM115** [JakeSteam/blog-personal#18]
Just to let you know that https://github.com/JakeSteam/blog-personal/blob/main/_posts/2023-01-08-complete-guide-to-forza-horizon-5-badges.md might need an update.  
  
it will have 3 new player badges, as confirmed [here](https://support.forzamotorsport.net/hc/en-us/articles/29558330078099-FH5-Release-Notes-May-21st-2024), but it's hard to find more info. they will be time-limited. You can see them here : https://www.youtube.com/live/4F1dDss1tdo?si=cQ0DwcjA39c2WbA9&t=2080 (34:40)

**Comment by JakeSteam** [comment]
Hey, thanks! I'm still playing every week to get cars etc, so I'll update the post once they're in the game and I can get screenshots 🙂
